'use client'
import { useState } from 'react'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import {
  SiTypescript,
  SiPostgresql,
  SiExpress,
  SiReact,
  SiNodedotjs,
  SiMongodb,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiTailwindcss,
  SiBootstrap,
  SiVite,
  SiNextdotjs,
  SiSequelize,
  SiMui,
} from 'react-icons/si'
import Image from 'next/image'
import Link from 'next/link'
import { PROJECTS } from '../projects'
import ProjectCard from '../components/ProjectCard/ProjectCard'
import AttributeCard from '@/components/Attribute/AttributeCard'
export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Bobby Walsh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </Head>

      <main className="bg-orange-100 dark:bg-gray-900 px-10 md:px-20 lg:px-40 p-3 ">
        <section className="bg-yellow-50 dark:bg-gray-800 min-h-screen rounded-xl p-4 shadow-lg">
          <nav className="py-10 mb-12 flex justify-between px-10">
            <h1 className="text-xl dark:text-gray-300">Developed By Bobby Walsh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl dark:text-gray-300"
                />
              </li>
              <li>
                <Link
                  className="transition-all bg-orange-300 hover:bg-orange-500  px-4 py-2 rounded-md ml-8 
                    dark:bg-gray-200 dark:hover:bg-gray-600"
                  href="/Documents/resume.pdf"
                  download
                >
                  Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 dark:text-gray-300  text-orange-400 font-medium md:text-6xl">Bobby Walsh</h2>
            <h3 className="text-2xl py-2 dark:text-gray-100 text-amber-950 md:text-3xl">Full-Stack Developer</h3>
            <p
              className="text-md py-5 leading-8
                dark:text-gray-100 text-amber-950
               md:text-xl max-w-xl mx-auto"
            >
              I am a full-stack developer with a versatile skill set in front-end and back-end development. With
              expertise in multiple programming languages and frameworks, I can create and maintain the entire software
              stack of web applications, from captivating user interfaces to robust server-side logic and seamless
              database integration. I'm eager to contribute my skills to innovative projects and make a positive impact
              in the field. Let's connect and explore opportunities together!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 dark:text-gray-100">
            <a href="https://twitter.com/CurrentlyBog" target="_blank" rel="noreferrer">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/bobbydwalsh/" target="_blank" rel="noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/CurrentlyBob" target="_blank" rel="noreferrer">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src="/avatar.png"
              alt="avatar"
              width={0}
              height={0}
              sizes="100vw"
              style={{ width: '100%', height: 'auto' }}
            />
          </div>
        </section>
        <section>
          <div className="my-5">
            <h3 className="text-3xl py-2 dark:text-gray-100 text-orange-500">Skills</h3>
            <div className="grid gap-4 justify-center grid-rows-2 grid-flow-col">
              <SiTypescript size={48} className="text-typeScript" />
              <SiPostgresql size={48} className="text-postgre" />
              <SiExpress size={48} className="dark:text-white" />
              <SiReact size={48} className="text-react" />
              <SiNodedotjs size={48} className="text-nodeJs" />
              <SiMongodb size={48} className="text-mongo" />
              <SiJavascript size={48} className="text-js" />
              <SiHtml5 size={48} className="text-html" />
              <SiCss3 size={48} className="text-css" />
              <SiGit size={48} className="text-git" />
              <SiTailwindcss size={48} className="text-tailwind" />
              <SiBootstrap size={48} className="text-bootstrap" />
              <SiVite size={48} className="text-vite" />
              <SiNextdotjs size={48} className="dark:text-white" />
              <SiSequelize size={48} className="text-sequel" />
              <SiMui size={48} className="text-mui" />
            </div>
          </div>
          <div className="lg:flex gap-10 justify-center">
            <AttributeCard
              imageSrc="/psychology.png"
              altText="psych-image"
              title="User-Centered Design"
              description="Applying psychology principles to create intuitive and user-friendly digital experiences"
              specializations={['Cognitive Psychology', 'Behavioral Analysis', 'Usability Testing']}
            />
            <AttributeCard
              imageSrc="/coding.png"
              altText="code-image"
              title="Software Craftsmanship"
              description="Transforming ideas into functional software solutions through elegant coding practices"
              specializations={['Quality Assurance', 'Backend Engineering', 'Agile Development']}
            />
            <AttributeCard
              imageSrc="/learn.png"
              altText="learn-image"
              title="Learning Enthusiast"
              description="Quickly adapting to new technologies, my passion for staying ahead drives my professional growth"
              specializations={['Adaptive Problem Solving', 'Continuous Learning', 'Collaborative Innovation']}
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-orange-500 dark:text-gray-300">Portfolio</h3>
          </div>
          <p className="text-md py-2 leading-8 text-amber-950 dark:text-gray-100">
            Welcome to my portfolio showcasing a variety of web projects. Each project incorporates
            <span className="text-orange-600 dark:text-gray-400"> JavaScript</span> and
            <span className="text-orange-600 dark:text-gray-400"> CSS</span> to create dynamic and stylish web
            experiences. Additionally, I utilized the following technologies in specific projects:
            <span className="text-orange-600 dark:text-gray-400"> React</span>,
            <span className="text-orange-600 dark:text-gray-400"> Bootstrap</span>,
            <span className="text-orange-600 dark:text-gray-400"> Tailwind</span>,
            <span className="text-orange-600 dark:text-gray-400"> MongoDB</span>,
            <span className="text-orange-600 dark:text-gray-400"> Express</span>,
            <span className="text-orange-600 dark:text-gray-400"> Mongoose</span>, and
            <span className="text-orange-600 dark:text-gray-400"> Node</span>.
          </p>
          <div className="flex flec-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {PROJECTS.map((project, index) => (
              <ProjectCard
                key={index}
                imageUrl={project.imageUrl}
                imageAlt={project.imageAlt}
                gitHubLink={project.gitHubLink}
                deployLink={project.deployLink}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}
