import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bobby Walsh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-orange-100 px-10">
        <section className=" bg-amber-100 min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed By Bobby Walsh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-yellow-400 to-orange-400 text-white px-4 py-2 rounded-md ml-8"
                  href="https://www.linkedin.com/in/robert-walsh-461b58267/"
                >
                  LinkedIn
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-orange-400 font-medium">Bobby Walsh</h2>
            <h3 className="text-2xl py-2 text-amber-950">Full-Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-amber-950 te">
              I am a full-stack developer with a versatile skill set in front-end and back-end development. With
              expertise in multiple programming languages and frameworks, I can create and maintain the entire software
              stack of web applications, from captivating user interfaces to robust server-side logic and seamless
              database integration.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-amber-950">
            <a href="https://twitter.com/CurrentlyBog">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/robert-walsh-461b58267/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/CurrentlyBob">
              <AiFillGithub />
            </a>
          </div>
        </section>
      </main>
    </div>
  )
}
