'use client'
import { useState } from 'react'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import {
  SiTypescript,
  SiPostgresql,
  SiExpress,
  SiReact,
  SiNodedotjs,
  SiMongodb,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiTailwindcss,
  SiBootstrap,
  SiVite,
  SiNextdotjs,
  SiSequelize,
} from 'react-icons/si'
import Image from 'next/image'
import Link from 'next/link'
import { PROJECTS } from '../projects'
import ProjectCard from '../components/ProjectCard/ProjectCard'
export default function Home() {
  const [darkMode, setDarkMode] = useState(false)



  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Bobby Walsh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
      </Head>

      <main className="bg-orange-100 dark:bg-gray-900 px-10 md:px-20 lg:px-40 ">
        <section className="bg-amber-100 dark:bg-gray-800 min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between px-10">
            <h1 className="text-xl font-burtons dark:text-gray-300">Developed By Bobby Walsh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl" />
              </li>
              <li>
                <Link
                  className="transition-all bg-orange-500 hover:bg-orange-800 text-white px-4 py-2 rounded-md ml-8 
                    dark:from-gray-400 dark:to-gray-600"
                  href="/Documents/resume.pdf"
                  download
                >
                  Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 dark:text-gray-300  text-orange-400 font-medium md:text-6xl">Bobby Walsh</h2>
            <h3 className="text-2xl py-2 dark:text-gray-100 text-amber-950 md:text-3xl">Full-Stack Developer</h3>
            <p
              className="text-md py-5 leading-8
                dark:text-gray-100 text-amber-950
               md:text-xl max-w-xl mx-auto"
            >
              I am a full-stack developer with a versatile skill set in front-end and back-end development. With
              expertise in multiple programming languages and frameworks, I can create and maintain the entire software
              stack of web applications, from captivating user interfaces to robust server-side logic and seamless
              database integration. I'm eager to contribute my skills to innovative projects and make a positive impact
              in the field. Let's connect and explore opportunities together!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 dark:text-gray-100">
            <a href="https://twitter.com/CurrentlyBog" target="_blank" rel="noreferrer">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/bobbydwalsh/" target="_blank" rel="noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/CurrentlyBob" target="_blank" rel="noreferrer">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image 
              src="/avatar.png" 
              alt="avatar" 
              width={0}
              height={0}
              sizes="100vw"
              style={{ width: '100%', height: 'auto' }} />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-100 text-orange-500">Skills</h3>
            <div className="flex flex-wrap gap-4">
              <SiTypescript size={48} />
              <SiPostgresql size={48} />
              <SiExpress size={48} />
              <SiReact size={48} />
              <SiNodedotjs size={48} />
              <SiMongodb size={48} />
              <SiJavascript size={48} />
              <SiHtml5 size={48} />
              <SiCss3 size={48} />
              <SiGit size={48} />
              <SiTailwindcss size={48} />
              <SiBootstrap size={48} />
              <SiVite size={48} />
              <SiNextdotjs size={48} />
              <SiSequelize size={48} />
            </div>
          </div>
          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-[600px] bg-gray-300">
              <div className="flex justify-center">
                <Image src="/psychology.png" alt="psych-image" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100 text-orange-500">User-Centered Design</h3>
              <p className="py-2 dark: text-gray-400">
                Applying psychology principles to create intuitive and user-friendly digital experiences
              </p>
              <h4 className="py-4 dark:text-gray-100 text-orange-600">Specializations</h4>
              <p className="py-1 dark:text-gray-300 text-amber-950">Cognitive Psychology</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Behavioral Analysis</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Usability Testing</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-[600px]">
              <div className="flex justify-center">
                <Image src="/coding.png" alt="code-image" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100 text-orange-500">
                Software Craftsmanship
              </h3>
              <p className="py-2 dark: text-gray-400">
                Transforming ideas into functional software solutions through elegant coding practices
              </p>
              <h4 className="py-4 dark:text-gray-100 text-orange-600">Specializations</h4>
              <p className="py-1 dark:text-gray-300 text-amber-950">Quality Assurance</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Backend Engineering</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Agile Development</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-[600px]">
              <div className="flex justify-center">
                <Image src="/learn.png" alt="learn-image" width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100 text-orange-500">Learning Enthusiast</h3>
              <p className="py-2 dark: text-gray-400">
                Quickly adapting to new technologies, my passion for staying ahead drives my professional growth
              </p>
              <h4 className="py-4 dark:text-gray-100 text-orange-600">Specializations</h4>
              <p className="py-1 dark:text-gray-300 text-amber-950">Adaptive Problem Solving</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Continuous Learning</p>
              <p className="py-1 dark:text-gray-300 text-amber-950">Collaborative Innovation</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-300">Portfolio</h3>
          </div>
          <p className="text-md py-2 leading-8 text-amber-950 dark:text-gray-100">
            Welcome to my portfolio showcasing a variety of web projects. Each project incorporates
            <span className="text-orange-600 dark:text-gray-400">JavaScript</span> and
            <span className="text-orange-600 dark:text-gray-400">CSS</span> to create dynamic and stylish web
            experiences. Additionally, I utilized the following technologies in specific projects:
            <span className="text-orange-600 dark:text-gray-400">React</span>,
            <span className="text-orange-600 dark:text-gray-400">Bootstrap</span>,
            <span className="text-orange-600 dark:text-gray-400">MongoDB</span>,
            <span className="text-orange-600 dark:text-gray-400">Express</span>,
            <span className="text-orange-600 dark:text-gray-400">Mongoose</span>, and
            <span className="text-orange-600 dark:text-gray-400"> Node</span>.
          </p>
          <div className="flex flec-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {PROJECTS.map((project, index) => (
              <ProjectCard
                key={index}
                imageUrl={project.imageUrl}
                imageAlt={project.imageAlt}
                gitHubLink={project.gitHubLink}
                deployLink={project.deployLink}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}
